config/routes.rb
Rails.application.routes.draw do
  get "/breeds/random", to: "breeds#random"

  resources :dog_sizes do
    resources :breeds, shallow: true do
      # collection do
      #   get :random
      # end
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "dog_sizes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/breed.rb
# == Schema Information
#
# Table name: breeds
#
#  id          :bigint           not null, primary key
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  dog_size_id :bigint           not null
#
# Indexes
#
#  index_breeds_on_dog_size_id  (dog_size_id)
#
# Foreign Keys
#
#  fk_rails_...  (dog_size_id => dog_sizes.id)
#
class Breed < ApplicationRecord
  belongs_to :dog_size
  has_one_attached :image

  validates :name, presence: true
end

app/models/dog_size.rb
# == Schema Information
#
# Table name: dog_sizes
#
#  id          :bigint           not null, primary key
#  description :text             default("weight ..-.. and height ..-..")
#  size        :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class DogSize < ApplicationRecord
  has_many :breeds
  has_one_attached :image

  validates :size, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/breeds_controller.rb
class BreedsController < ApplicationController
  before_action :set_breed, only: %i[ show edit update destroy ]
  before_action :set_dog_size, only: %i[ index create ]

  def index
    @breeds = @dog_size.breeds
  end

  def show; end

  def new
    @dog_size = DogSize.find(params[:dog_size_id])
    @breed = @dog_size.breeds.build
  end

  def edit
    @breed = Breed.find(params[:id])
    @dog_size = @breed.dog_size
  end

  def create
    @breed = @dog_size.breeds.build(breed_params)

    respond_to do |format|
      if @breed.save
        format.html { redirect_to @breed, notice: "Breed was successfully created." }
        format.json { render :show, status: :created, location: @breed }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @breed.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @breed.update(breed_params)
        format.html { redirect_to @breed, notice: "Breed was successfully updated." }
        format.json { render :show, status: :ok, location: @breed }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @breed.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @breed.destroy

    respond_to do |format|
      format.html { redirect_to dog_size_breeds_path(@breed.dog_size), notice: "Breed was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def random
    breed = Breed.order("RANDOM()").first

    render json: {
      id: breed.id,
      name: breed.name,
      image_url: breed.image.attached? ? url_for(breed.image.variant(resize_to_limit: [300, 300])) : nil
    }
  end

  private

    def set_breed
      @breed = Breed.find(params[:id])
    end

    def set_dog_size
      @dog_size = DogSize.find(params[:dog_size_id])
    end

    def breed_params
      params.require(:breed).permit(:name, :image)
    end
end

app/controllers/dog_sizes_controller.rb
class DogSizesController < ApplicationController
  before_action :set_dog_size, only: %i[ show edit update destroy ]

  def index
    @dog_sizes = DogSize.all
  end

  def show
    redirect_to dog_size_breeds_path(params[:id])
  end

  def new
    @dog_size = DogSize.new
  end

  def edit; end

  def create
    @dog_size = DogSize.new(dog_size_params)

    respond_to do |format|
      if @dog_size.save
        format.html { redirect_to @dog_size, notice: "Dog size was successfully created." }
        format.json { render :show, status: :created, location: @dog_size }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dog_size.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @dog_size.update(dog_size_params)
        format.html { redirect_to @dog_size, notice: "Dog size was successfully updated." }
        format.json { render :show, status: :ok, location: @dog_size }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dog_size.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @dog_size.destroy

    respond_to do |format|
      format.html { redirect_to dog_sizes_path, status: :see_other, notice: "Dog size was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_dog_size
      @dog_size = DogSize.find(params[:id])
    end

    def dog_size_params
      params.require(:dog_size).permit(:size, :description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/breeds/_breed.html.erb
<div id="<%= dom_id breed %>">
</div>

app/views/breeds/_form.html.slim
= form_with(model: (@breed.persisted? ? @breed : [@dog_size, @breed]), local: true, html: { multipart: true }) do |form|

  - if @breed.errors.any?
    div style="color: red"
      h2 = pluralize(@breed.errors.count, "error")
      ul
        - @breed.errors.full_messages.each do |msg|
          li = msg

  div
    = form.label :name
    br
    = form.text_field :name

  div
    = form.label :image
    br
    = form.file_field :image

  - if @breed.image.attached?
    p Текущее изображение:
    = image_tag @breed.image.variant(resize_to_limit: [300, 300])

  div
    = form.submit class: "btn"

app/views/breeds/edit.html.slim
h1 Editing breed

div
  = link_to "Back", dog_size_breeds_path(@breed.dog_size), class: "btn"

= render "form", breed: @breed

app/views/breeds/index.html.slim
p.notice = notice

h1 = "#{@dog_size.size} breeds"

= link_to "Back", dog_sizes_path, class: "btn"
= link_to "New breed", new_dog_size_breed_path(@dog_size), class: "btn"

table
  tr
    td
      - if @dog_size.image.attached?
        = image_tag url_for(@dog_size.image.variant(resize_to_limit: [300, 300]))
    td
      p
        strong Size:
        = @dog_size.size

      p
        strong Description:
        = @dog_size.description

      div
        .actions
          = link_to "Edit", edit_dog_size_path(@dog_size), class: "btn"
          = button_to "Delete", @dog_size, method: :delete, class: "btn", data: { confirm: 'Are you sure you want to delete this dog size?' }

table
  thead
    tr
      th Name
      th Actions
  tbody
    - @breeds.each do |breed|
      tr
        td = link_to breed.name, breed, class: "breed_name"
        td
          .actions
            = link_to "Edit", edit_breed_path(breed), class: "btn"
            = button_to "Delete", breed, method: :delete, class: "btn", data: { confirm: 'Are you sure you want to delete this breed?' }

app/views/breeds/new.html.slim
h1 New breed

= render "form", breed: @breed
br
div
  = link_to "Back to breeds", dog_size_breeds_path(@breed.dog_size), class: "btn"

app/views/breeds/show.html.slim
p.notice = notice

= render @breed

= link_to "Back to #{@breed.dog_size.size.downcase} dogs", dog_size_breeds_path(@breed.dog_size), class: "btn"

table
  tr
    td
      - if @breed.image.attached?
        = image_tag url_for(@breed.image.variant(resize_to_limit: [300, 300]))
    td
      p
        strong Breed name:
        = @breed.name

      div
        = link_to "Edit", edit_breed_path(@breed), class: "btn"

app/views/dog_sizes/_form.html.slim
= form_with(model: @dog_size, local: true, html: { multipart: true }) do |form|
  - if @dog_size.errors.any?
    #error_explanation style="color: red"
      h2 = pluralize(@dog_size.errors.count, "error")
      ul
        - @dog_size.errors.full_messages.each do |message|
          li = message

  div
    = form.label :size
    br
    = form.text_field :size

  div
    = form.label :description
    br
    = form.text_area :description

  div
    = form.label :image
    br
    = form.file_field :image

    - if @dog_size.image.attached?
      p Текущее изображение:
      = image_tag @dog_size.image.variant(resize_to_limit: [300, 300])

  div
    = form.submit class: "btn"

app/views/dog_sizes/edit.html.slim
= form_with model: @dog_size, local: true, html: { multipart: true } do |form|
  - if @dog_size.errors.any?
    #error_explanation
      h2= pluralize(@dog_size.errors.count, "error") + " prohibited this dog_size from being saved:"
      ul
        - @dog_size.errors.full_messages.each do |message|
          li= message

  div
    = form.label :size
    = form.text_field :size

  div
    = form.label :description
    = form.text_area :description

  div
    = form.label :image
    = form.file_field :image

    - if @dog_size.image.attached?
      div
        = image_tag @dog_size.image.variant(resize_to_limit: [300, 300])

  div
    = form.submit class: "btn"

app/views/dog_sizes/index.html.slim
p.notice = notice

h1 Choose Category

= link_to "New Dog Size", new_dog_size_path, class: "btn"

button.btn data-controller="random-breed" data-action="click->random-breed#load" Choice your dog

#random-breed-container

.container
  .grid
    - @dog_sizes.each do |dog_size|
      .card data-controller="dog-card" data-action="click->dog-card#choiceSize"
        - if dog_size.image.attached?
          = image_tag url_for(dog_size.image.variant(resize_to_limit: [300, 300])), alt: dog_size.size
        .card-title
          = link_to dog_size.size, dog_size, class: "btn", data: { "dog-card-target": "link" }

app/views/dog_sizes/new.html.slim
h1 New dog size

= render "form", dog_size: @dog_size
br
div
  = link_to "Back to dog sizes", dog_sizes_path, class: "btn"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DogClassification</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "style", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <h1><%= link_to "Dogs", root_path %></h1>
    </header>

    <main class="container">
      <%= yield %>
    </main>

    <footer style="text-align: center; padding: 1rem 0;">
      &copy; <%= Date.today.year %> DogClassification Project
    </footer>
  </body>
</html>